http:
 host: "0.0.0.0"
 port: "8081"
 path: "/api/*"
 
systemApi:
 item:
  http:
   host: "system-item-db-api.us-e2.cloudhub.io"
   port: "80"
   path: "api/items"
 orderItem:
  http:
   host: "system-orderItem-db-api.us-e2.cloudhub.io"
   port: "80"
   path: "api/orderItems"
 order:
  http:
   host: "system-order-db-api.us-e2.cloudhub.io"
   port: "80"
   path: "api/orders"