#%RAML 1.0 NamedExample
 
{
  "orderId": 1,
  "placementDate": "2019-10-03",
  "customerName": "john john",
  "orderItems": [
    {
      "orderItemId": 1,
      "itemId": 1,
      "itemCount": 1,
      "itemName": "productA",
      "iItemCost": 100
    }
  ]
}